### ISSUE TITLE
Esx skin error	xPlayer.setMaxWeight(defaultMaxWeight)

### ISSUE THREAD

**Issue by kekev2001** [ESX-Org/esx_skin#32] opened 2019-10-28 13:15 UTC
SCRIPT ERROR: @esx_skin/server/main.lua:14: attempt to call a nil value (field 'setMaxWeight')
![Knipsel](https://user-images.githubusercontent.com/56051728/67681333-69aa8a80-f98d-11e9-8de0-7267d349a405.PNG)

**Comment by CALauer** [comment] 2019-10-31 12:22
Also have this issue.

**Comment by CALauer** [comment] 2019-10-31 14:27
HotFix - I made a duplicate of my server only reinstalling es_extended and that fixed my issue. Hope this helps.

**Comment by sisanc6** [comment] 2019-12-03 13:43
SCRIPT ERROR: @esx_skin/server/main.lua:14: attempt to call a nil value (field 'setMaxWeight')
https://i.imgur.com/DmlCJLM.png

**Comment by 2ratheflouterman** [comment] 2020-04-11 10:45
> SCRIPT ERROR: @esx_skin/server/main.lua:14: attempt to call a nil value (field 'setMaxWeight')
> https://i.imgur.com/DmlCJLM.png

Did you fix it ?

**Closed** 2020-04-11 11:36 UTC

**Comment by 32minds** [comment] 2020-08-13 02:42
fixed?
