### ISSUE TITLE
Memory usage!!

### ISSUE THREAD

**Issue by benzon** [ESX-Org/esx_skin#19] opened 2019-01-22 15:46 UTC
The current memory ussage of esx_skin is not good sorry to say.

It uses 50mb+ with out reason, not EUP cloath or what so ever.

**Comment by benzon** [comment] 2019-01-22 16:10
it's not the skin resource thats the issue, the issue is actually esx_menu_default i guess, after replacing with an old version that gives the warning, of ms usage, there is no issue or what so ever with memory usage.

**Comment by SLuuuuuuG** [comment] 2019-02-21 23:27
Which version of the esx_menu_default did you find that works and does not display that message

**Comment by ElPumpo** [comment] 2019-03-19 21:23
Duplicate of #16

**Closed by ElPumpo** 2019-03-19 21:23 UTC
